eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerDNSName: yopter.vpc
    eurekaServerPort: ${server.port}
    eurekaServerURLContext: eureka
    useDnsForFetchingServiceUrls: true
    region: us-east-2
